[project]
name = "bookerypd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.1.2",
    "djangorestframework>=3.15.2",
    "pydantic>=2.6.1",
    "django-filter>=23.5",
]
